Codeit-Part4-SFJs/WDYTA

- tailwind.config.ts
> ex) #20
> lg 속성이 안먹는 이슈를 발견하였습니다! tailwind css에 lg를 추가했습니다!
> bug : tailwind css screens lg 속성 추가

- src/shared/ui/Input/Password/index.tsx
- src/shared/ui/Input/PasswordCheck/index.tsx
- src/shared/ui/Input/image/index.tsx
> ex) #36 
> IIcon 색상 추가하였습니다. 색상을 잘못 입력한 부분도 수정했습니다!
>
> feat: Icon 사용 시 color 추가

- src/shared/@common/apis/constants/API.ts
> common: 공통 API 및 auth 파일 삭제

- src/shared/@common/apis/auth.ts
- src/shared/@common/apis/image.ts
- src/shared/@common/apis/oauth.ts
> #72 
> API fetch 작업 완료
> 회원가입도 같이 올리려다가 지금 폼 제출 관련 오류가 있어서 먼저 올립니다 !
> feat: Oauth, Image, Auth API 세팅

- src/components/Login/LoginForm.tsx
- src/components/Login/hooks/useLoginMutation.ts
- src/components/Login/loginAction.ts
- src/components/Register/RegisterForm.tsx
- tailwind.config.ts
> #79 
> 로그인 후 쿠키 저장
> 로그아웃은 @suMin-97 수민님 PR 머지 후 추가할 예정입니다!
> 로그인 페이지 API 연동 및 기능 구현

- src/app/[category]/[product]/page.tsx
- src/middleware.ts
- src/shared/ui/Menu/Gnb/Gnb.tsx
- src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
- src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
- src/shared/ui/Menu/Gnb/GnbUser.tsx
- src/shared/ui/Menu/Gnb/types/gnbType.ts
> #82
> 로그인 유무에 따른 GnB 분기처리
> middleware 기본형 세팅
> 로그아웃 버튼에 새로고침 추가
> 로그인 여부에 따라 GnB 바뀝니다!
> 아직 로그아웃은 UI만 있는것으로 추후 연아님 PR 머지 되면 사용 가능합니다. 그 전까지 로그아웃은 수동으로 쿠키 지워주세요!
> 저희 나중에 프로젝트 완료 되면 상황에 따른 리다이렉션이 필요한데, 각각의 페이지에서 작업하면 나중에 체크하기 어려워서 미들웨어로 관리 할 수 있게 기본형 만들었습니다. 세세한 설정도 추가로 가능하며, 모든 프로젝트 완성 후 유저 플로우 따라서 리다이렉션 여부 결정하면 될거 같습니다. 주석 상세하게 달아뒀으니 확인 부탁드립니다!
> @yeona813 추가로 연아님! 로그아웃으로 쿠키를 지우면 GnB에도 쿠키 삭제 여부가 반영되도록 새로고침 추가했습니다. 로그아웃 서버 액션 구현 되시면 여기에 넣어주시면 됩니다!!
> api: 로그인 상태에 따른 GnB 분기 처리

- src/components/Login/loginAction.ts
- src/shared/@common/utils/index.ts
- src/shared/@common/utils/logoutAction.ts
- src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
- src/shared/ui/Menu/Gnb/logoutAction.ts
> #85 
> 로그아웃 버튼 클릭 시 쿠키 삭제 
임의로 로그아웃 버튼 클릭 시 수행되도록 테스트 한 결과 !
> @suMin-97 수민님 PR 머지되면 해당 위치에 실행되도록 구현할 예정
> feat: 로그아웃 action 기능 구현

- src/shared/@common/apis/follow.ts
- src/shared/@common/apis/product.ts
api 수정했습니다!
> ex) #이슈번호, #이슈번호
>
> fix: follow, product api 세팅 수정

- src/app/[category]/[product]/queryOptions.ts
- src/components/Detail/ProductDetail/DetailFavoriteButton.tsx
- src/components/Detail/ProductDetail/FavoriteButton.tsx
- src/components/Detail/ProductDetail/ProductDetail.tsx
- src/components/Detail/ProductDetail/hooks/index.ts
- src/components/Detail/ProductDetail/hooks/useFavoriteMutation.ts
- src/components/Detail/ProductReviews/ControlButtons.tsx
- src/components/Detail/ProductReviews/LikeButton.tsx
- src/components/Detail/ProductReviews/ProductReviews.tsx
- src/components/Detail/ProductReviews/ReviewCard.tsx
- src/components/Detail/ProductReviews/ReviewLikeButton.tsx
- src/components/Detail/ProductReviews/ReviewProfile.tsx
- src/components/Detail/ProductReviews/hooks/index.ts
- src/components/Detail/ProductReviews/hooks/useDeleteReviewMutation.ts
- src/components/Detail/ProductReviews/hooks/useLikeMutation.ts
- src/components/Detail/ProductStatistics/ProductStatistics.tsx
- src/components/Detail/ProductStatistics/Statistic.tsx
- src/components/Detail/types/productDetailType.ts
- src/components/Detail/types/productReviewsType.ts
- src/shared/@common/apis/product.ts
> #97 
> 타입명 수정
> queryOption 제너릭 설정
> 변수명 직관적으로 수정
> 멘토님 코드리뷰 반영
> 연아님 코드리뷰 반영: 찜 버튼 캐시 부분 수정 (if 제거)
> 이전 PR이 3개로 나누어져 있었어서 PR 리뷰 및 멘토링 내용 반영했습니다!
> refactor: 상품 상세 페이지 리팩토링

- src/components/Detail/ProductDetail/modal/EditModal.tsx
- src/components/Detail/ProductDetail/modal/ReviewModal.tsx
- src/components/Detail/ProductDetail/modal/index.ts
- src/shared/ui/Input/TextBox/TextBoxInput.stories.tsx
- src/shared/ui/Input/TextBox/TextBoxInput.tsx
- src/shared/ui/Input/image/ImageInput.tsx
> #106 
> 상품 리뷰 모달 UI
> 상품 편집 모달 UI
UI에 집중하여 작업했습니다. 
아직 모달 포탈 작업이 되지 않아 우선 그냥 임시로 border 흰색으로 해서 잘 보이게 해놨습니다 .
- PC
- Tablet
- Mobile
- 리뷰 별점
>
> 우선 모든게 다 임시로 한 것이라 CSS 빼고는 변동이 많이 될 것 같습니다.
> 상품 리뷰 모달, 상품 편집 모달 UI 작업

- src/app/[category]/homeQueryKeyFactories.ts
- src/app/page.tsx
- src/components/Home/MainProducts/MainProducts.tsx
- src/components/Home/RankingCard/RankingCard.tsx
- src/components/Home/ReviewerRanking/ReviewerRanking.tsx
- src/components/Home/constants/HOME_SORT_OPTIONS.ts
- src/components/Home/mock/CATEGORY_LIST_MOCK.ts
- src/components/Home/mock/HOME_PRODUCT_LIST_MOCK.ts
- src/components/Home/mock/RANKING_LIST_MOCK.ts
- src/components/Home/skeletons/SkeletonMainCard.tsx
- src/components/Home/skeletons/SkeletonMainProducts.tsx
- src/components/Home/skeletons/SkeletonMainTitle.tsx
- src/components/Home/skeletons/SkeletonRankingCard.tsx
- src/components/Home/skeletons/SkeletonRankingTitle.tsx
- src/components/Home/skeletons/SkeletonReviewerRanking.tsx
- src/components/Home/types/ProductType.ts
- src/components/Home/types/RankingType.ts
- src/shared/@common/apis/constants/API.ts
- src/shared/@common/apis/product.ts
- src/shared/@common/utils/adaptRanking.ts
- src/shared/ui/Button/Floating/Floating.tsx
- src/shared/ui/Chip/RankingChip/RankingChip.stories.tsx
- src/shared/ui/Chip/RankingChip/RankingChip.tsx
#47 #65 #102 #103 
- 홈페이지 UI 구현 (+반응형) 및 리팩토링
- skeleton 제작
- API URL 추가, getHomeProductList 패칭 함수 추가, 홈페이지 쿼리키 설정
>
사실 본격적인 API 연동 작업을 조금 진행하다가... 
첫단추 잘 끼우는 게 중요할 것 같아서 일단 쪼개서 먼저 올려봅니다!!
그냥 홈페이지랑, 카테고리 선택했을때의 홈페이지랑 각각 뿌려지는 데이터가 조금 달라서, 
API 패칭함수도 따로 getHomeProductList 함수 추가로 만들어보았는데요! 
혹시 제가 이렇게 API 초기 설정한 게 어떤지 한번 면밀히 검토해주시면 감사하겠습니다!!
> feat: 홈페이지 UI 구현 및 리팩토링, skeleton, API 초기 세팅

- src/components/@common/AlertModal.tsx
> #110 
> AlertModal UI 구현
>
> 에러 메세지 위치나 디자인적으로 괜찮은지 한번 확인 부탁드릴게요!!
> feat: AlertModal UI 구현

- src/components/@common/ProductCard.tsx
- src/components/Home/RankingCard/RankingCard.tsx
- src/shared/@common/apis/product.ts
- **빌드 오류(syntaxError) 수정 및 랭킹카드 Link태그 경로 수정**
>
> fix: 빌드 오류 해결 및 랭킹카드 Link태그 경로 수정

- .github/workflows/CICD.yml
> S3에 올라갈 build 파일 생성 yml 추가
>
> feat: yml build 액션 추가

- .github/workflows/CICD.yml
> feat: SSH 키

- .github/workflows/CICD.yml
> feat: yarn build

- .github/workflows/CICD.yml
> feat: SSH 수정

- src/components/@common/modal/ProductModal.tsx
- src/components/Detail/modal/EditModal.tsx
- src/components/Detail/modal/ReviewModal.tsx
- src/shared/@common/utils/changeImage.ts
> #159 
> alert 제거 후 setErrorMessage로 에러 관리
>
> @hyunjun9788 , @linason-esc 님의 파일을 수정하였습니다!
> refactor: alert 제거 후 방식 수정

- src/components/Profile/modal/EditModal.tsx
> fix: setErrorMessage 빠진 부분 추가
> fix: setErrorMessage 빠진 부분 추가

- src/components/Detail/ProductDetail/ProductDetail.tsx
- src/components/Detail/ProductDetail/hooks/useEditProductMutation.ts
- src/components/Detail/ProductReviews/ReviewProfile.tsx
- src/components/Detail/ProductReviews/hooks/useCreateReviewMutation.tsx
- src/components/Detail/modal/EditModal.tsx
- src/components/Detail/modal/ReviewModal.tsx
> #152 
> 상품 리뷰, 편집 모달 disabled 속성 추가 및 캐시 설정
>
> disabled 속성을 원래 mutation에서 isPending 그거를 사용하려다가 mutation을 두개 쓰니까 isPending을 어떻게 해야할지 몰라.. 우선 useState로 했놨습니다. 이 부분과 관련하여 도움을 주신다면 정말 감사하겠습니다!! 편하게 말씀해주십쇼!!!
> fix : 상품 리뷰, 편집 모달 disabled 속성 추가 및 캐시 설정

- src/components/Detail/ProductDetail/ShareButtons.tsx
> 카카오톡 공유된 메세지의 공유 이미지 수정 및 버튼의 URL 수정
> @mangang0713 주형님 공유하기도 수정 부탁드려요! 아직 머지가 안되어서 제가 할수가 없습니다...
> fix: 공유 이미지 수정 및 버튼의 URL 수정

- package.json
> chore: 버전 업

- package.json
- src/shared/ui/Menu/Gnb/GnbHamburgerMenu.tsx
- src/shared/ui/Menu/Gnb/GnbSettingButton.tsx
- src/shared/ui/Menu/Gnb/GnbUser.tsx
- src/shared/ui/Menu/Gnb/types/gnbType.ts
- src/shared/ui/Menu/SideMenu/SideMenuTab.tsx
> 로그인 시 GnB의 검색바 위치 이동 수정 및 햄버거 메뉴 사용 후 자동 닫기 추가
> fix: 로그인 시 GnB의 검색바 위치 이동 수정 및 햄버거 메뉴 사용 후 자동 닫기 추가

- src/components/Detail/modal/EditModal.tsx
- src/components/Detail/modal/ReviewEditModal.tsx
- src/components/Detail/modal/ReviewModal.tsx
- src/components/Home/modal/AddModal.tsx
- src/components/Login/LoginForm.tsx
- src/components/Oauth/SocialLoginForm.tsx
- src/components/Profile/modal/EditModal.tsx
- src/components/Register/RegisterForm.tsx
- src/shared/ui/Menu/Gnb/GnbSearch.tsx
> fix: autoComplete=off 추가
